name: Release Rescale Interlink
run-name: ${{ github.actor }} is releasing Rescale Interlink

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  windows-build:
    runs-on: windows-latest
    environment: production
    if: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run build script
        run: ./build/build_dist.ps1 -ReleaseTag "${{ github.ref_name }}"
        shell: pwsh

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Sign executable using Azure Trusted Signing
        uses: azure/artifact-signing-action@v0
        with:
          files-folder: ${{ github.workspace }}\_build\bin
          files-folder-filter: exe
          file-digest: SHA256
          timestamp-rfc3161: http://timestamp.acs.microsoft.com
          timestamp-digest: SHA256
          endpoint: https://eus.codesigning.azure.net/
          code-signing-account-name: ${{ secrets.AZURE_TRUSTED_SIGNING_ACCOUNT }}
          certificate-profile-name: ${{ secrets.AZURE_TRUSTED_SIGNING_PROFILE }}
          exclude-environment-credential: true
          exclude-workload-identity-credential: true
          exclude-managed-identity-credential: true
          exclude-shared-token-cache-credential: true
          exclude-visual-studio-credential: true
          exclude-visual-studio-code-credential: true
          exclude-azure-cli-credential: false
          exclude-azure-powershell-credential: true
          exclude-azure-developer-cli-credential: true
          exclude-interactive-browser-credential: true

      - name: Zip portable release
        run: Compress-Archive -Path ${{ github.workspace }}\_build\bin\* -DestinationPath rescale-interlink-${{ github.ref_name }}-win_amd64.zip
        shell: pwsh

      - name: Create installer
        run: ./build/build_installer.ps1 -ReleaseTag "${{ github.ref_name }}" -MsiName "rescale-interlink-${{ github.ref_name }}-win_amd64.msi"
        shell: pwsh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rescale-interlink-win_amd64
          path: rescale-interlink-${{ github.ref_name }}-win_amd64.*

  macos-build:
    runs-on: macos-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Apple Certificate
        env:
          CERTIFICATE_BASE64: ${{ secrets.MACOS_P12_B64 }}
          CERT_PASSWORD: ${{ secrets.MACOS_P12_PASSWORD }}
          KEYCHAIN_PASSWORD: "temporary-keychain-password"
        run: |
          # Create temporary keychain
          CERT_PATH=$RUNNER_TEMP/build_certificate.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # Import certificate from secrets
          echo -n "$CERTIFICATE_BASE64" | base64 --decode -o $CERT_PATH

          # Setup keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # Import certificate to keychain
          security import $CERT_PATH -P "$CERT_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

      - name: Build Executable
        run: |
          curl -O https://REMOVED.example.com/rescale-int

      - name: Sign Executable
        env:
          # This should match the "Common Name" of your certificate (e.g., "Developer ID Application: Name (ID)")
          IDENTITY: "Rescale, Inc"
        run: |
          codesign --force --options runtime --sign "$IDENTITY" rescale-int

      - name: Create Zip Archive
        run: |
          zip rescale-interlink-${{ github.ref_name }}-macos_amd64.zip rescale-int

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rescale-interlink-win_amd64
          path: rescale-interlink-${{ github.ref_name }}-win_amd64.*

  release:
    name: Create Release
    needs: windows-build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
          pattern: rescale-interlink-${{ github.ref_name }}-* # Downloads only artifacts for this version
          merge-multiple: true # Flattens the folder structure for easier uploading

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          # This will automatically pick up all files in the directory
          files: ./artifacts/*
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
