name: Release Rescale Interlink
run-name: ${{ github.actor }} is releasing Rescale Interlink

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run build script
        if: false
        run: ./build/build_dist.ps1 -ReleaseTag "${{ github.ref_name }}"
        shell: pwsh

      - name: Download pre-build
        run: |
          New-Item -Path "_build\bin" -ItemType Directory -Force
          Invoke-WebRequest -Uri "https://REMOVED.example.com/rescale-int.exe" -OutFile "_build\bin\rescale-int.exe"
        shell: pwsh

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Sign executable using Azure Trusted Signing
        uses: azure/artifact-signing-action@v0
        with:
          files-folder: ${{ github.workspace }}\_build\bin
          files-folder-filter: exe
          file-digest: SHA256
          timestamp-rfc3161: http://timestamp.acs.microsoft.com
          timestamp-digest: SHA256
          endpoint: https://eus.codesigning.azure.net/
          exclude-environment-credential: true
          exclude-workload-identity-credential: true
          exclude-managed-identity-credential: true
          exclude-shared-token-cache-credential: true
          exclude-visual-studio-credential: true
          exclude-visual-studio-code-credential: true
          exclude-azure-cli-credential: false
          exclude-azure-powershell-credential: true
          exclude-azure-developer-cli-credential: true
          exclude-interactive-browser-credential: true

      - name: Zip portable release
        run: Compress-Archive -Path ${{ github.workspace }}\_build\bin\* -DestinationPath rescale-interlink-${{ github.ref_name }}-win_amd64.zip
        shell: pwsh

      - name: Create installer
        run: ./build/build_dist.ps1 -ReleaseTag "${{ github.ref_name }}" -MsiName "rescale-interlink-${{ github.ref_name }}-win_amd64.msi"
        shell: pwsh

      - name: Upload Portable Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rescale-interlink-${{ github.ref_name }}-win_amd64.zip
          path: rescale-interlink-${{ github.ref_name }}-win_amd64.zip

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rescale-interlink-${{ github.ref_name }}-win_amd64.msi
          path: rescale-interlink-${{ github.ref_name }}-win_amd64.msi

  release:
    name: Create Release
    needs: windows-build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
          pattern: rescale-interlink-${{ github.ref_name }}-* # Downloads only artifacts for this version
          merge-multiple: true # Flattens the folder structure for easier uploading

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          # This will automatically pick up all files in the directory
          files: ./artifacts/*
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
